### ISSUE TITLE
Plugin ccat_reranker fails to load due to typing_extensions version conflict (TypeIs missing)

### ISSUE THREAD

**Issue by Andreh7777** [nickprock/ccat_reranker#2]
Description:
During installation and startup of the ccat_reranker plugin in Cheshire Cat (1.9.2), the plugin fails to load due to an import error related to typing_extensions. The issue arises from a version conflict between torch and unstructured, which have incompatible requirements for the typing_extensions package.

ERROR:
cheshire_cat_core  | Installing collected packages: nvidia-cusparselt-cu12, typing_extensions, triton, safetensors, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, transformers, torch, sentence-transformers
cheshire_cat_core  |   Attempting uninstall: typing_extensions
cheshire_cat_core  |     Found existing installation: typing_extensions 4.9.0
cheshire_cat_core  |     Uninstalling typing_extensions-4.9.0:
cheshire_cat_core  |       Successfully uninstalled typing_extensions-4.9.0
cheshire_cat_core  | 
cheshire_cat_core  | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cheshire_cat_core  | unstructured 0.12.6 requires typing-extensions==4.9.0, but you have typing-extensions 4.14.0 which is incompatible.
cheshire_cat_core  | Successfully installed networkx-3.4.2 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 safetensors-0.5.3 sentence-transformers-4.0.2 torch-2.7.1 transformers-4.53.0 triton-3.3.1 typing_extensions-4.14.0
cheshire_cat_core  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
cheshire_cat_core  | ERROR:     Error in cat.plugins.ccat_reranker.ccat_reranker. Unable to load plugin ccat_reranker
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/app/cat/mad_hatter/plugin.py", line 316, in _load_decorated_functions
cheshire_cat_core  |     plugin_module = importlib.import_module(py_filename)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
cheshire_cat_core  |     return _bootstrap._gcd_import(name[level:], package, level)
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cheshire_cat_core  |   File "/app/cat/plugins/ccat_reranker/ccat_reranker.py", line 3, in <module>
cheshire_cat_core  |     from sentence_transformers import CrossEncoder
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 9, in <module>
cheshire_cat_core  |     from sentence_transformers.backend import (
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/backend.py", line 11, in <module>
cheshire_cat_core  |     from sentence_transformers.util import disable_datasets_caching, is_datasets_available
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/util.py", line 17, in <module>
cheshire_cat_core  |     import torch
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 71, in <module>
cheshire_cat_core  |     from typing_extensions import TypeIs as _TypeIs
cheshire_cat_core  | ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)

**Comment by nickprock** [comment]
Hi @Andreh7777 , I updated the sentence-transformers version. I think it's ok now.
Thanks for the issue.

**Comment by Andreh7777** [comment]
Good morning, thanks for your help. I'm testing the new version but i get the same error:

cheshire_cat_core  | ERROR:     Error in cat.plugins.ccat_reranker.ccat_reranker. Unable to load plugin ccat_reranker
cheshire_cat_core  | Traceback (most recent call last):
cheshire_cat_core  |   File "/app/cat/mad_hatter/plugin.py", line 316, in _load_decorated_functions
cheshire_cat_core  |     plugin_module = importlib.import_module(py_filename)
cheshire_cat_core  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
cheshire_cat_core  |     return _bootstrap._gcd_import(name[level:], package, level)
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
cheshire_cat_core  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
cheshire_cat_core  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cheshire_cat_core  |   File "/app/cat/plugins/ccat_reranker/ccat_reranker.py", line 3, in <module>
cheshire_cat_core  |     from sentence_transformers import CrossEncoder
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 9, in <module>
cheshire_cat_core  |     from sentence_transformers.backend import (
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/backend.py", line 11, in <module>
cheshire_cat_core  |     from sentence_transformers.util import disable_datasets_caching, is_datasets_available
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/sentence_transformers/util.py", line 17, in <module>
cheshire_cat_core  |     import torch
cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 71, in <module>
cheshire_cat_core  |     from typing_extensions import TypeIs as _TypeIs
cheshire_cat_core  | ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)
cheshire_cat_core  | WARNING:   To resolve any problem related to Cheshire Cat ReRanker plugin, contact the creator using github issue at the link https://github.com/nickprock/ccat_reranker

**Comment by Andreh7777** [comment]
I solved the problem by updating the type_extensions dependency

**Comment by nickprock** [comment]
which version did you use?

I tried to insert a new `unstructured` version, it should be fix

**Comment by Andreh7777** [comment]
I am using Cheshirecat AI 1.9.2 (latest version available). The plugin worked fine in Cheshirecat AI version 1.9.1.
I will try the new version asap.

sentence-transformers==4.1.0
unstructured==0.18.1
